export const TEXT_ON_SCREEN_HOOKS = {
  foundEarly: [
    "Small artist. Real song. Right algorithm.",
    "No label push. Just a song that needs ears.",
    "Before the numbers arrive, tell me if this feels real.",
    "Found before the crowd caught up.",
    "The algorithm does get it right sometimes.",
    "This has no machine behind it. Just meaning.",
    "No playlist push. No industry machine. Just a real song.",
    "This is the part before people pretend they were early.",
    "Before this has numbers, be honest — would you save it?",
    "You found this before the rollout had a budget.",
    "Not trending yet. Just looking for the right people.",
    "This is what discovery sounds like before the crowd arrives.",
    "If this reached you, it probably wasn’t by accident.",
    "This song is still small enough to feel personal.",
    "Before this reaches more people, I want honest ears on it.",
    "No hype yet. Just a track trying to find its people.",
    "This is the version before the world catches up.",
    "For the people who like finding artists before everyone else.",
    "You’re not late. You’re early enough to matter.",
  ],

  emotionalPov: [
    "POV: you're exhausted but quitting would hurt more.",
    "POV: you keep acting calm but your mind never stops.",
    "POV: you're carrying more pressure than you talk about.",
    "POV: you're tired but life keeps asking for more.",
    "POV: you're trying to move forward but your mind keeps looking back.",
    "POV: you're finally winning but it still feels lonely.",
    "POV: nobody knows how much this dream is costing you.",
    "POV: you needed music that sounded like pressure.",
    "POV: you look calm because explaining it would take too long.",
    "POV: you’re not okay, but you’re still showing up.",
    "POV: you’re proud of yourself and exhausted at the same time.",
    "POV: you’re trying to build while healing from what broke you.",
    "POV: you’re tired of surviving, but not ready to give up.",
    "POV: you made peace with pressure because it never left.",
    "POV: you keep going because stopping would feel worse.",
    "POV: your mind is loud, but your face stays calm.",
    "POV: you’re becoming stronger than your circumstances.",
  ],

  identity: [
    
    "Rap for people who feel too much but say too little.",
    "For the ones carrying pressure like it's normal.",
    "Music for people building something nobody sees yet.",
    "This one is for anyone who refuses to fold.",
    "For people who needed a reason to keep going.",
    "For the ones who feel everything quietly.",
    "Music for people who turn silence into fuel.",
    "For anyone trying to become more than their situation.",
    "For people who needed the song before they needed the artist.",
    "Rap for people with too many thoughts and not enough answers.",
    "For people chasing something they can’t fully explain yet.",
    "Music for the ones who smile through pressure.",
    "For anyone who feels behind but refuses to stop.",
    "For the ones building confidence in private.",
    "This is not for everyone. That’s the point.",
  ],

  relatableTruths: [
    
    "Being busy is not the same as moving forward.",
    "Sometimes the dream costs more than you expected.",
    "Some songs are really survival notes.",
    "The hardest part is staying consistent when nobody claps yet.",
    "Some people confuse silence with peace.",
    "Growth looks calm until you're the one going through it.",
    "The pressure gets quiet, but it does not disappear.",
    "The dream sounds better before you see the cost.",
    "Not every strong person feels strong.",
    "Progress can look boring while it’s happening.",
    "Sometimes discipline is just pain with direction.",
    "You can be grateful and still be tired.",
    "Some chapters only make sense after you survive them.",
    "Nobody sees the version of you that almost gave up.",
    "Sometimes you’re not unmotivated — you’re just drained.",
  ],

transformation: [
  "You survived things that used to break you.",
  "You're becoming someone your old self needed.",
  "The old version of me wouldn't recognise this life.",
  "Healing changed more than I expected.",
  "Growth leaves versions of you behind.",
  "The struggle shaped more than the success.",
  "You become what you repeatedly survive.",
],

successCost: [
  "Some dreams ask for more than expected.",
  "Success has a receipt nobody talks about.",
  "The climb costs something.",
  "Some goals are expensive in ways money can't measure.",
  "Winning doesn't erase sacrifice.",
  "Every level asks for something new.",
  "People celebrate results, not the price.",
  "Growth creates distance sometimes.",
  "The dream is beautiful and exhausting.",
  "Not every sacrifice feels worth it immediately.",
],

mentalNoise: [
  "Some thoughts never fully clock out.",
  "Calm outside doesn't mean calm inside.",
  "The overthinking never got the memo.",
  "Some pressure becomes background noise.",
  "Your brain keeps working after the day ends.",
  "Not every storm looks dramatic.",
],

  lyricLeadIns: [
    "This line sounded normal until life got real.",
    "One lyric. The whole feeling.",
    "The line I almost deleted says the most.",
    "This bar is for anyone pretending they're fine.",
    "The hook is cool, but this line tells the truth.",
    "This lyric aged better than I expected.",
    "Some lyrics only make sense after you've lived them.",
    "This line explains the whole song.",
    "The second bar hits harder than the first.",
    "This lyric was too honest to leave hidden.",
    "This is the line I almost kept to myself.",
    "This lyric says what I couldn’t say normally.",
    "The most honest part is easy to miss.",
    "This bar sounds different when you’ve lived it.",
    "This line carries the whole emotion.",
    "I wrote this line before I understood it.",
    "This lyric is doing more than rhyming.",
    "The quietest line says the loudest thing.",
    "This part is where the song stops pretending.",
    "This lyric deserves more than one listen.",
  ],

  underdogArtist: [
    "Trying to make it as a small artist is not for the weak.",
    "No team. No label. Just the song.",
    "Still not famous. Still posting.",
    "Every save helps this reach the right people.",
    "I made this before anyone was watching.",
    "This song has no budget, just belief.",
    "Small artist trying to find the right ears.",
    "If this reaches you, that genuinely means something.",
    "No playlist push. No industry machine. Just a real song.",
    "Building a music career one post at a time.",
    "No viral moment yet. Still showing up.",
    "This is what independent really looks like.",
    "No cosign. No shortcut. Just consistency.",
    "I’m still early, but the music is real.",
    "This song is doing its best without a machine.",
    "Trying to find listeners without pretending to be bigger than I am.",
    "This is the grind people don’t see before they say you came from nowhere.",
    "I don’t need everyone. I just need the right people first.",
    "Independent artist. Real pressure. Real song.",
    "This is me betting on the music before anyone else does.",
  ],

  contrarian: [
    "They said meaningful rap does not work anymore.",
    "They said nobody listens to lyrics now.",
    "They said small artists cannot break through anymore.",
    "They said people only care about trends.",
    "They said emotional music cannot still be hard.",
    "They said consistency matters more than talent. They were half right.",
    "They said this sound would not find people.",
    "They said I needed a gimmick. I chose honesty.",
    "They said being different was the problem.",
    "They said nobody wants substance anymore.",
    "They said deep music doesn’t travel. I disagree.",
    "They said short attention spans killed real lyrics.",
    "They said honest music is too slow for the algorithm.",
    "They said you need to chase trends. I’d rather build a world.",
    "They said music has to be simple to connect.",
    "They said vulnerability makes rap soft.",
    "They said people don’t care about the meaning anymore.",
    "They said the algorithm only rewards noise.",
    "They said nobody wants to think while listening.",
    "They said this was too real to work online.",
  ],
    viewerInvolvement: [
    "If you're seeing this, you're officially part of the first wave.",
    "Your algorithm just handed you something before everyone else found it.",
    "You found this early enough to say you were here first.",
    "If this reaches you now, you're not late — you're early.",
    "This is the part where a few people find it before the crowd arrives.",
    "You just found a song small enough to still feel personal.",
    "If this ends up growing, remember you saw it here first.",
    "You are now legally allowed to say you discovered this early.",
    "Only a few people know this exists right now.",
    "This is your sign to stop scrolling and claim early fan status.",
  ],

  commentBaitButHuman: [
    "Tell me what this sounds like to you.",
    "Be honest — what genre would you call this?",
    "If this made you feel something, tell me where you're listening from.",
    "If this lyric hit you, I want to know which line did it.",
    "Would you play this in the car or skip it?",
    "What would you call this sound?",
    "If this was on your playlist, where would it fit?",
    "Does this feel like night music or morning music?",
    "If you found this randomly, would you stay?",
    "What part would you replay?",
  ],

  antiMarketing: [
    "I'm too tired to sell this properly, but this part means a lot.",
    "Not even going to pretend I know how to market this song.",
    "This is not a polished ad. I just want the right ears on it.",
    "I almost didn't post this because promo feels awkward.",
    "Trying to promote music without sounding cringe is harder than making it.",
    "No big campaign. Just a song I care about.",
    "I don't know if this is how you're supposed to promote music.",
    "This is me trying to show the song without begging people to listen.",
    "I would rather let the song speak than over-explain it.",
    "If this only reaches one person who gets it, that's enough.",
  ],

  humourDiscovery: [
    "Your algorithm finally clocked in today.",
    "You scrolled too slow and now you're part of the rollout.",
    "This is either your new favourite song or a weird interruption.",
    "The algorithm said you needed a small artist today.",
    "Accidentally discovering small artists is character development.",
    "If you stayed longer than 3 seconds, you're basically involved now.",
    "This song has no marketing budget so I'm relying on vibes.",
    "I asked the algorithm for help and it sent me you.",
    "If this flops, at least we were all here together.",
    "This post is held together by hope and one good hook.",
  ],

  artistStruggle: [
  "Spent 4 months making this. The algorithm gets 4 seconds.",
  "Writing the song was easier than posting it.",
  "I can write verses. Marketing still scares me.",
  "The song took weeks. The caption took longer.",
  "Nobody tells you the hard part is getting people to listen.",
  "Made this instead of sleeping.",
  "I've replayed this song 500 times. Curious what you hear.",
  "I nearly didn't post this.",
  "This song sat in my notes for months.",
  "The overthinking almost won."
],

  viewerDiscovery: [
  "Your algorithm finally clocked in.",
  "You found this before everyone else did.",
  "Congratulations. You're early.",
  "The algorithm accidentally did its job.",
  "One day this video will be embarrassing to repost.",
  "You're looking at the before picture.",
  "This might be the smallest crowd this song ever sees.",
  "Caught us before the screenshots start.",
  "You just discovered an artist in the wild.",
  "The algorithm handed you a side quest."
],

 identityHooks: [
  "Music for people who still listen properly.",
  "For people who care about lyrics more than trends.",
  "This isn't background music.",
  "Some songs are meant to be felt, not skimmed.",
  "For people who miss when music had something to say.",
  "Music for overthinkers.",
  "Built for deep thinkers and long walks.",
  "For listeners, not scrollers.",
  "This song won't be for everyone.",
  "Maybe that's the point."
],

curiosityHooks: [
  "The last line changes everything.",
  "Wait for the second half.",
  "This wasn't supposed to make the final version.",
  "The weirdest part became the best part.",
  "I didn't realise what this line meant until later.",
  "This verse nearly got deleted.",
  "The ending hits harder than the beginning.",
  "One lyric changed the whole song.",
  "I wrote this by accident.",
  "Tell me if I'm hearing this wrong."
],

audienceChallenge: [
  "Tell me if this deserves a skip.",
  "What genre is this actually?",
  "Name someone doing this better.",
  "Would you save this or scroll?",
  "Be honest. Is this hard or am I biased?",
  "I genuinely don't know who this song is for.",
  "Convince me this isn't the best part.",
  "Am I hearing this wrong?",
  "Would this survive your playlist purge?",
  "What's the first thing this reminds you of?"
],

musicCulture: [
  "Every genre has one artist you're supposed to like.",
  "The best song on the album is rarely the single.",
  "Music fans hear details nobody else notices.",
  "People judge genres before they hear the song.",
  "Your favourite song probably wasn't the biggest one.",
  "The replay button tells the truth.",
  "The comments section knows before the charts do.",
  "Some songs are made for headphones only.",
],

hotTakes: [
  "Most artists release the wrong song first.",
  "Good music gets buried every day.",
  "Being relatable is overrated.",
  "Most playlists are too safe.",
  "The algorithm isn't the reason people skipped it.",
  "Artists spend too much time promoting average songs.",
  "The best music advice is usually boring.",
  "Viral doesn't automatically mean good.",
],

artistHumour: [
  "Checking Spotify again like it owes me money.",
  "Me pretending one stream wasn't my own phone.",
  "Spent six months making this and three hours choosing the cover.",
  "Refreshing stats won't change them but here we are.",
  "Release day is just controlled panic.",
  "The song is finished. The overthinking isn't.",
  "Me explaining the song badly after spending months writing it.",
],

fanCulture: [
  "Every fanbase has one song they defend with their life.",
  "Music fans remember lyrics better than birthdays.",
  "The best songs usually find the right people slowly.",
  "Every listener has one song they refuse to skip.",
  "That feeling when a song becomes part of your personality.",
  "The replay button is the real review section.",
],

musicObservations: [
  "The weirdest thing about release day is nobody else knows it's release day.",
  "The caption usually takes longer than people think.",
  "People discover songs in completely random ways.",
  "A song can change your life without changing the charts.",
  "Most listeners never know how many versions existed first.",
  "The smallest moments usually become the favourite parts.",
],



}