export const TEXT_ON_SCREEN_HOOKS = {
  foundEarly: [
    "Small artist. Real song. Right algorithm.",
    "No label push. Just a song that needs ears.",
    "Not viral yet. Just honest enough to matter.",
    "Before the numbers arrive, tell me if this feels real.",
    "Found before the crowd caught up.",
    "The algorithm does get it right sometimes.",
    "This has no machine behind it. Just meaning.",
    "No playlist push. No industry machine. Just a real song.",
    "This is the part before people pretend they were early.",
    "Before this has numbers, be honest — would you save it?",
    "You found this before the rollout had a budget.",
    "Not trending yet. Just looking for the right people.",
    "This is what discovery sounds like before the crowd arrives.",
    "If this reached you, it probably wasn’t by accident.",
    "This song is still small enough to feel personal.",
    "Before this reaches more people, I want honest ears on it.",
    "No hype yet. Just a track trying to find its people.",
    "This is the version before the world catches up.",
    "For the people who like finding artists before everyone else.",
    "You’re not late. You’re early enough to matter.",
  ],

  emotionalPov: [
    "POV: you're exhausted but quitting would hurt more.",
    "POV: you keep acting calm but your mind never stops.",
    "POV: you're carrying more pressure than you talk about.",
    "POV: you're tired but life keeps asking for more.",
    "POV: you're trying to move forward but your mind keeps looking back.",
    "POV: you're finally winning but it still feels lonely.",
    "POV: nobody knows how much this dream is costing you.",
    "POV: you're becoming someone your old self needed.",
    "POV: you needed music that sounded like pressure.",
    "POV: you're healing and hungry at the same time.",
    "POV: you look calm because explaining it would take too long.",
    "POV: you’re not okay, but you’re still showing up.",
    "POV: life keeps testing the version of you that wants better.",
    "POV: you’re proud of yourself and exhausted at the same time.",
    "POV: you’re trying to build while healing from what broke you.",
    "POV: you’re tired of surviving, but not ready to give up.",
    "POV: you made peace with pressure because it never left.",
    "POV: you keep going because stopping would feel worse.",
    "POV: your mind is loud, but your face stays calm.",
    "POV: you’re becoming stronger than your circumstances.",
  ],

  identity: [
    "Music for people who overthink everything.",
    "Rap for people who feel too much but say too little.",
    "For the ones carrying pressure like it's normal.",
    "For people who are tired but not finished.",
    "For anyone pretending they're fine.",
    "This is for deep thinkers with heavy hearts.",
    "Music for people building something nobody sees yet.",
    "For the people who turn pain into progress.",
    "This one is for anyone who refuses to fold.",
    "For people who needed a reason to keep going.",
    "For the ones who feel everything quietly.",
    "Music for people who turn silence into fuel.",
    "For anyone trying to become more than their situation.",
    "For people who needed the song before they needed the artist.",
    "Rap for people with too many thoughts and not enough answers.",
    "For people chasing something they can’t fully explain yet.",
    "Music for the ones who smile through pressure.",
    "For anyone who feels behind but refuses to stop.",
    "For the ones building confidence in private.",
    "This is not for everyone. That’s the point.",
  ],

  relatableTruths: [
    "Nobody talks about how lonely growth can be.",
    "Being busy is not the same as moving forward.",
    "Sometimes the dream costs more than you expected.",
    "Some songs are really survival notes.",
    "Some wins feel empty when certain people are missing.",
    "The hardest part is staying consistent when nobody claps yet.",
    "Some people confuse silence with peace.",
    "Growth looks calm until you're the one going through it.",
    "The pressure gets quiet, but it does not disappear.",
    "Sometimes trying not to quit is the whole story.",
    "The dream sounds better before you see the cost.",
    "Not every strong person feels strong.",
    "Progress can look boring while it’s happening.",
    "Sometimes discipline is just pain with direction.",
    "You can be grateful and still be tired.",
    "The hardest battles are the ones nobody can see.",
    "Some chapters only make sense after you survive them.",
    "Nobody sees the version of you that almost gave up.",
    "Sometimes you’re not unmotivated — you’re just drained.",
    "Healing and ambition are a heavy combination.",
  ],

  growth: [
  "The version of you from last year would be proud.",
  "Growth changes you before anybody notices.",
  "You don't realise how far you've come until you look back.",
  "Some progress is invisible until it's undeniable.",
  "The climb feels different when you're living it.",
  "Becoming who you needed takes time.",
  "Growth often feels like losing comfort.",
  "You're further than your doubts admit.",
  "Some chapters only make sense afterwards.",
  "The person you're becoming would thank you.",
],

transformation: [
  "You survived things that used to break you.",
  "You're becoming someone your old self needed.",
  "The old version of me wouldn't recognise this life.",
  "Healing changed more than I expected.",
  "Some pain turns into perspective.",
  "You don't stay the same after certain years.",
  "Growth leaves versions of you behind.",
  "This song came from a different version of me.",
  "The struggle shaped more than the success.",
  "You become what you repeatedly survive.",
],

selfDoubt: [
  "Confidence is quieter than people think.",
  "Some days the doubt gets loud.",
  "You can believe and question yourself simultaneously.",
  "Nobody talks about the second-guessing.",
  "Even progress can feel uncertain.",
  "Sometimes the hardest battle is your own mind.",
  "Doubt doesn't disappear when things improve.",
  "The dream gets bigger, so do the questions.",
  "Not every confident person feels confident.",
  "Some days belief feels like work.",
],

successCost: [
  "Some dreams ask for more than expected.",
  "Success has a receipt nobody talks about.",
  "The climb costs something.",
  "Some goals are expensive in ways money can't measure.",
  "Winning doesn't erase sacrifice.",
  "Every level asks for something new.",
  "People celebrate results, not the price.",
  "Growth creates distance sometimes.",
  "The dream is beautiful and exhausting.",
  "Not every sacrifice feels worth it immediately.",
],

mentalNoise: [
  "The loudest battles happen silently.",
  "Your mind doesn't always know how to rest.",
  "Some thoughts never fully clock out.",
  "Calm outside doesn't mean calm inside.",
  "The overthinking never got the memo.",
  "Some pressure becomes background noise.",
  "Peace feels unfamiliar sometimes.",
  "Your brain keeps working after the day ends.",
  "Not every storm looks dramatic.",
  "Some noise only you can hear.",
],

  lyricLeadIns: [
    "This line sounded normal until life got real.",
    "One lyric. The whole feeling.",
    "The line I almost deleted says the most.",
    "This bar is for anyone pretending they're fine.",
    "The hook is cool, but this line tells the truth.",
    "This lyric aged better than I expected.",
    "Some lyrics only make sense after you've lived them.",
    "This line explains the whole song.",
    "The second bar hits harder than the first.",
    "This lyric was too honest to leave hidden.",
    "This is the line I almost kept to myself.",
    "This lyric says what I couldn’t say normally.",
    "The most honest part is easy to miss.",
    "This bar sounds different when you’ve lived it.",
    "This line carries the whole emotion.",
    "I wrote this line before I understood it.",
    "This lyric is doing more than rhyming.",
    "The quietest line says the loudest thing.",
    "This part is where the song stops pretending.",
    "This lyric deserves more than one listen.",
  ],

  underdogArtist: [
    "Trying to make it as a small artist is not for the weak.",
    "No team. No label. Just the song.",
    "Still not famous. Still posting.",
    "Every save helps this reach the right people.",
    "I made this before anyone was watching.",
    "This song has no budget, just belief.",
    "Small artist trying to find the right ears.",
    "If this reaches you, that genuinely means something.",
    "No playlist push. No industry machine. Just a real song.",
    "Building a music career one post at a time.",
    "No viral moment yet. Still showing up.",
    "This is what independent really looks like.",
    "No cosign. No shortcut. Just consistency.",
    "I’m still early, but the music is real.",
    "This song is doing its best without a machine.",
    "Trying to find listeners without pretending to be bigger than I am.",
    "This is the grind people don’t see before they say you came from nowhere.",
    "I don’t need everyone. I just need the right people first.",
    "Independent artist. Real pressure. Real song.",
    "This is me betting on the music before anyone else does.",
  ],

  contrarian: [
    "They said meaningful rap does not work anymore.",
    "They said nobody listens to lyrics now.",
    "They said small artists cannot break through anymore.",
    "They said people only care about trends.",
    "They said emotional music cannot still be hard.",
    "They said consistency matters more than talent. They were half right.",
    "They said this sound would not find people.",
    "They said I needed a gimmick. I chose honesty.",
    "They said being different was the problem.",
    "They said nobody wants substance anymore.",
    "They said deep music doesn’t travel. I disagree.",
    "They said short attention spans killed real lyrics.",
    "They said honest music is too slow for the algorithm.",
    "They said you need to chase trends. I’d rather build a world.",
    "They said music has to be simple to connect.",
    "They said vulnerability makes rap soft.",
    "They said people don’t care about the meaning anymore.",
    "They said the algorithm only rewards noise.",
    "They said nobody wants to think while listening.",
    "They said this was too real to work online.",
  ],
}